image: gitpod/workspace-mongodb
ports:
- port: 8050
  onOpen: open-preview
- port: 5000
- port: 8080
- port: 27017
- port: 8888
- port: 1050
tasks:
- init: /workspace/gitpod-dash/run.sh
- command: cp -r .jupyter /home/gitpod/
- command: mongod
- command: pip3 install -r requirements.txt && (python3 data_acquire.py & python3 app.py)
